#!/bin/bash

score=0
max=0

echo "Tests positifs (fichiers dans tests/good/)"

for f in tests/good/*.py; do
    max=`expr $max + 1`;
    echo $f
    expected=tests/good/`basename $f .py`.out
    rm -f out
    if $1 $f > out; then
	if cmp --quiet out $expected; then
	    score=`expr $score + 1`;
	else
	    echo "  ECHEC : mauvaise sortie pour $f"
	fi
    else
	echo "  ECHEC de l'interprétation pour $f"
    fi
done
echo

echo "Tests négatifs (fichiers dans tests/bad/)"

for f in tests/bad/*.py; do
    max=`expr $max + 1`;
    echo $f
    rm -f out
    if $1 $f > out 2>&1; then
	echo "  ECHEC : l'évaluation de $f devrait échouer"
    else
        if grep -q "^error:" out; then
	    score=`expr $score + 1`;
        else
            echo "  ECHEC : devrait afficher 'error'"
        fi
    fi
done

echo
percent=`expr 100 \* $score / $max`;
echo "Score: $score / $max tests, soit $percent%"
