#!/bin/zsh

if [[ $# != 1 ]]; then
  print -u2 "Usage: $0 output"
  exit 1
fi

dir=${0:h}
out=$1

files=($dir/*.png)
file=$files[RANDOM%$#files+1]

convert $file \
  -resize 1920x1080 \
  -background black \
  -gravity center \
  -extent 1920x1080 \
  -font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \
  -pointsize 14 \
  -gravity southeast \
  -strokewidth 2 \
  -stroke white -fill none  -annotate +11+11 "Venez à la Kâlloc le 25/04 en K-Fêt ! Images par Modestine Pellet et Mattéo Wei" \
  -stroke none  -fill black -annotate +11+11 "Venez à la Kâlloc le 25/04 en K-Fêt ! Images par Modestine Pellet et Mattéo Wei"\
  $out
