DROP TABLE Persons CASCADE;
DROP TABLE Curriculums CASCADE; 
DROP TABLE Courses CASCADE; 
DROP TABLE Validations CASCADE; 
DROP TABLE Credits CASCADE; 
DROP TABLE Grades CASCADE; 
DROP TABLE Programs CASCADE;
