# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157G0Q-RA7xWCwlQHQyJuzScQTYPliWhb
"""

from typing import Any
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# --- EXERCISE 1: La disparition (No 'e' or 'E) ---
class LaDisparition:
    """
    Generate text without ever using the letter 'e' or 'E'.
    For this, you must use model() directly: model(input_ids) yields logits.
    You need to manually adjust the logits to forbid tokens containing 'e' or 'E'.
    REQUIREMENT: Do NOT use model.generate().
    """
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.forbidden_token_ids = set()
        # Iterate through the vocabulary and identify tokens containing 'e' or 'E'
        for token_string, token_id in self.tokenizer.vocab.items():
            if 'e' in token_string.lower():
                self.forbidden_token_ids.add(token_id)

    def __call__(self, prompt, max_tokens=30):
        # Tokenize input prompt
        prompt = "Question: " + prompt + "\nAnswer in a single sentence: "
        input_ids = self.tokenizer.encode(prompt, return_tensors="pt").to(self.model.device)

        generated_ids = []
        for i in range(max_tokens):
            # Get model logits for the next token
            outputs = self.model(input_ids)
            logits = outputs.logits
            next_token_logits = logits[:, -1, :]

            # Create a mask to set forbidden token logits to negative infinity
            next_token_logits[:, list(self.forbidden_token_ids)] = float('-inf')

            next_token_id = torch.argmax(next_token_logits, dim=-1, keepdim=True)

            # Append the generated token to the sequence
            input_ids = torch.cat([input_ids, next_token_id], dim=-1)
            generated_ids.append(next_token_id.item())

            # Check for end-of-sequence token
            if next_token_id.item() == self.tokenizer.eos_token_id:
                break

        # Decode output tokens to string and return
        return self.tokenizer.decode(generated_ids, skip_special_tokens=True)

# --- EXERCISE 2: The Toulouse Sequence ---
class ToulouseSequence:
    """
    Generate text without ever using the word 'Toulouse'.
    For this, you must use model() directly: model(input_ids) yields logits.
    You need to manually adjust the logits. It is more difficult here because
    'Toulouse' is a multi-token word.
    REQUIREMENT: Do NOT use model.generate().
    """
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.forbidden_token_ids = set()
        for i in range(len("Toulouse")):
            w = "Toulouse"[:i]
            for t_id in self.tokenizer.encode("Toulouse", add_special_tokens=False):
                self.forbidden_token_ids.add(t_id)

    def __call__(self, prompt, max_tokens=30):
        # Tokenize input prompt
        prompt = "Question: " + prompt + "\nAnswer in a single sentence: "
        input_ids = self.tokenizer.encode(prompt, return_tensors="pt").to(self.model.device)
        generated_ids = []
        for i in range(max_tokens):
            # Get model logits for the next token
            outputs = self.model(input_ids)
            logits = outputs.logits
            next_token_logits = logits[:, -1, :]

            # Create a mask to set forbidden token logits to negative infinity
            next_token_logits[:, list(self.forbidden_token_ids)] = float('-inf')

            next_token_id = torch.argmax(next_token_logits, dim=-1, keepdim=True)

            # Append the generated token to the sequence
            input_ids = torch.cat([input_ids, next_token_id], dim=-1)
            generated_ids.append(next_token_id.item())

            # Check for end-of-sequence token
            if next_token_id.item() == self.tokenizer.eos_token_id:
                break

        # Decode output tokens to string and return
        return self.tokenizer.decode(generated_ids, skip_special_tokens=True)

if __name__ == "__main__":
    MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, dtype=torch.float16, device_map="auto")
    la_disparition_generator = LaDisparition(model, tokenizer)
    print("Ex 1 (No 'e'):", la_disparition_generator("Describe a cat."))
    toulouse_sequence_generator = ToulouseSequence(model, tokenizer)
    print("Ex 2 (No 'Toulouse'):", toulouse_sequence_generator("Where is the headquarters of Airbus located?"))

